from .register_page import RegisterPageView
from .login_page import LoginPageView
from .dashboard import DashboardView
from .logout_user import LogoutUserView
from .user_page import UserPageView
from .profile_page import ProfilePageView
from .products import ProductsView
from .customer import CustomersView
from .create_order import CreateOrderView
from .update_order import UpdateOrderView
from .delete_order import DeleteOrderView
